<?php

/**
 * @file
 * Provides Schema mapping for DCAT.
 */

/**
 * Implements hook_open_data_schema().
 */
function open_data_schema_dcat_open_data_schema() {
  $schemas_path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'open_data_schema_dcat') . '/data/';
  return array(
    array(
      'short_name' => 'dcat',
      'title' => 'DCAT-AP',
      'schema_file' => $schemas_path . 'dcatap-1.1.json',
      'description' => t('DCAT Schema. See https://gitlab.com/european-data-portal/ckan-dcatap-schema/blob/master/ckan-dcatap-1.1.json for more awesome details.'),
    ),
  );
}

/**
 * Implements hook_open_data_schema_map_xml_output_render_data_alter().
 */
function open_data_schema_dcat_open_data_schema_map_xml_output_render_data_alter(&$xml, &$api) {
  global $base_url;

  //If is dcat schema then add attributes on the xml root
  if ($api->api_schema == 'dcat') {
    $xml['@xmlns:foaf'] = "http://xmlns.com/foaf/0.1/";
    $xml['@xmlns:owl'] = "http://www.w3.org/2002/07/owl#";
    $xml['@xmlns:rdfs'] = "http://www.w3.org/2000/01/rdf-schema#";
    $xml['@xmlns:rdf'] = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
    $xml['@xmlns:dcat'] = "http://www.w3.org/ns/dcat#";
    $xml['@xmlns:dct'] = "http://purl.org/dc/terms/";
    $xml['@xmlns:adms'] = "http://www.w3.org/ns/adms#";
    $xml['@xmlns:dc'] = "http://purl.org/dc/elements/1.1/";
    $xml['@xmlns:time'] = "http://www.w3.org/2006/time#";

    //Add catalog information
    $catalog = array(
      'dct:title' => variable_get('site_name', t('Dataset')),
      'dct:description' =>  variable_get('site_slogan', t('Description')),
//      'dct:issued' => 'Issued',
//      'dct:modified' => 'Modified',
//      'dct:language' =>  'Language',
//      'dct:license' => 'License',
//      'dct:spatial' => 'Spatial',
      'foaf:homepage' => $base_url . '/search/type/dataset',
    );
    $xml = array('dcat:Catalog' => $catalog) + $xml;
  }
}
