<?php

/**
 * @file
 * Provides Schema mapping for DCAT.
 */

/**
 * Implements hook_open_data_schema().
 */
function open_data_schema_dcat_open_data_schema() {
  $schemas_path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'open_data_schema_dcat') . '/data/';
  return array(
    array(
      'short_name' => 'dcat',
      'title' => 'DCAT-AP',
      'schema_file' => $schemas_path . 'dcatap-1.1.json',
      'description' => t('DCAT Schema. See https://gitlab.com/european-data-portal/ckan-dcatap-schema/blob/master/ckan-dcatap-1.1.json for more awesome details.'),
    ),
    array(
      'short_name' => 'dcat_dataset',
      'title' => 'DCAT-AP (Dataset)',
      'schema_file' => $schemas_path . 'dataset-1.1.json',
      'description' => t('DCAT Schema (Dataset). See https://gitlab.com/european-data-portal/ckan-dcatap-schema/blob/master/ckan-dcatap-1.1.json for more awesome details.'),
    ),
  );
}

/**
 * Implements hook_open_data_schema_fill_references().
 */
function open_data_schema_dcat_open_data_schema_fill_references($schema_name, &$schema) {
  $module_path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'open_data_schema_dcat');
  switch ($schema_name) {
    case 'dcat':
    case 'dcat_dataset':
      $references = array(
        'dcat:Distribution',
        'dcat:contactPoint',
      );
      $files = array();
      // Process $ref keys to include referenced json file.
      foreach ($references as $key) {
        $json = $module_path . '/data/';
        if (isset($schema['properties'][$key]['anyOf'])) {
          $json = $json . $schema['properties'][$key]['anyOf'][0]['items']['$ref'];
        }
        elseif(isset($schema['properties'][$key]['$ref'])) {
          $json = $json . $schema['properties'][$key]['$ref'];
        }
        $json = file_get_contents($json);
        $json = drupal_json_decode($json);
        unset($json['$schema']);
        unset($json['id']);
        if (isset($schema['properties'][$key]['anyOf'])) {
          unset($json['title']);
          unset($schema['properties'][$key]['anyOf'][0]['items']['$ref']);
          if (isset($schema['properties'][$key]['anyOf'][0]['items']['minItems'])) {
            $schema['properties'][$key]['anyOf'][0]['minItems'] = $schema['properties'][$key]['anyOf'][0]['items']['minItems'];
          }
          if ($schema['properties'][$key]['anyOf'][0]['items']['uniqueItems']) {
            $schema['properties'][$key]['anyOf'][0]['uniqueItems'] = $schema['properties'][$key]['anyOf'][0]['items']['uniqueItems'];
          }
          $schema['properties'][$key]['anyOf'][0]['uniqueItems'] = $schema['properties'][$key]['anyOf'][0]['items']['uniqueItems'];
          $schema['properties'][$key]['anyOf'][0]['items'] = $json;
        }
        else {
          $schema['properties'][$key] = $json;
        }
      }
      break;
  }
}

/**
 * Implements hook_open_data_schema_map_xml_output_render_data_alter().
 */
function open_data_schema_dcat_open_data_schema_map_xml_output_render_data_alter(&$xml, &$api) {
  global $base_url;

  //If is dcat schema then add attributes on the xml root
  if ($api->api_schema == 'dcat' || $api->api_schema == 'dcat_dataset') {
    $xml['@xmlns:foaf'] = "http://xmlns.com/foaf/0.1/";
    $xml['@xmlns:owl'] = "http://www.w3.org/2002/07/owl#";
    $xml['@xmlns:rdfs'] = "http://www.w3.org/2000/01/rdf-schema#";
    $xml['@xmlns:rdf'] = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
    $xml['@xmlns:dcat'] = "http://www.w3.org/ns/dcat#";
    $xml['@xmlns:dct'] = "http://purl.org/dc/terms/";
    $xml['@xmlns:adms'] = "http://www.w3.org/ns/adms#";
    $xml['@xmlns:dc'] = "http://purl.org/dc/elements/1.1/";
    $xml['@xmlns:time'] = "http://www.w3.org/2006/time#";

    //Fix some data output (datetimes format, ...).
    if (!empty($xml['dcat:Dataset'])) {
      foreach ($xml['dcat:Dataset'] as &$dataset) {
         if (isset($dataset['dct:temporal'])) {
            $dataset['dct:temporal'][0]['schema:startDate']['@rdf:datatype'] = 'http://www.w3.org/2001/XMLSchema#date';
            $dataset['dct:temporal'][0]['schema:endDate']['@rdf:datatype'] = 'http://www.w3.org/2001/XMLSchema#date';
            $dataset['dct:temporal']['dct:PeriodOfTime'] = $dataset['dct:temporal'];
            unset ($dataset['dct:temporal']);
          }
      }
    }

    if ($api->api_schema == 'dcat') {
      //Add catalog information
      $catalog = array(
        'dct:title' => variable_get('site_name', t('Dataset')),
        'dct:description' =>  variable_get('site_slogan', t('Description')),
  //      'dct:issued' => 'Issued',
  //      'dct:modified' => 'Modified',
  //      'dct:language' =>  'Language',
  //      'dct:license' => 'License',
  //      'dct:spatial' => 'Spatial',
        'foaf:homepage' => $base_url . '/search/type/dataset',
      );
      $xml = array('dcat:Catalog' => $catalog) + $xml;
    }
  }
}

/**
 * Implements hook_page_alter().
 */
function open_data_schema_dcat_page_alter(&$page) {

  //If is the homepage then add the alternative url for catalog.xml
  if (drupal_is_front_page()) {
    drupal_add_html_head_link(array('rel' => 'alternate', 'type' => 'application/rdf+xml', 'href' => url('catalog.xml', array('absolute' => TRUE))));
  }

  //If is a dataset node add the link with filter for the specific dataset
  $node = menu_get_object();

  if (is_object($node) && $node->type == 'dataset') {
    $uuid = $node->uuid;
    $alias = drupal_get_path_alias('node/' . $node->nid);
    drupal_add_html_head_link(array('rel' => 'alternate', 'type' => 'application/rdf+xml', 'href' => url($alias . '.xml', array('absolute' => TRUE))));
  }
}

/**
 * Implements hook_url_inbound_alter().
 */
function open_data_schema_dcat_url_inbound_alter(&$path, $original_path, $path_language) {
  $extension = pathinfo($path, PATHINFO_EXTENSION);

  if ($extension == 'xml') {
    //Is trying to get dcat information from dataset?
    $path_alias = preg_replace('/\\.[^.\\s]{3,4}$/', '', $path);
    $internal_path = drupal_lookup_path('source', $path_alias, $path_language);
    $internal_path = explode('/', $internal_path);

    if (count($internal_path) == 2 && $internal_path[0] == 'node' && is_numeric($internal_path[1])) {
      $dataset = node_load($internal_path[1]);

      if ($dataset->type == 'dataset') {
        //Use dcat dataset endpoint
        $path = 'catalog/dataset.xml';
        $_GET['dct:identifier'] = $dataset->uuid;
      }
    }
  }
}

/**
 * Implements hook_url_outbound_alter().
 */
function open_data_schema_dcat_url_outbound_alter(&$path, &$options, $original_path) {
  if (preg_match('|^catalog/dataset\.xml(/.*)?|', $path, $matches)) {
    if (isset($options['query']['dct:identifier'])) {
      $uuid = $options['query']['dct:identifier'];
      $node = current(entity_uuid_load('node', array($uuid)));
      $path_alias = drupal_lookup_path('alias', 'node/' . $node->nid);

      $path = "$path_alias" . ".xml";
    }
  }
}
