<?php

/**
 * @file
 * Provides Schema mapping for DCAT.
 */

/**
 * Implements hook_open_data_schema().
 */
function open_data_schema_dcat_open_data_schema() {
  $schemas_path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'open_data_schema_dcat') . '/data/';
  return array(
    array(
      'short_name' => 'dcat',
      'title' => 'DCAT-AP',
      'schema_file' => $schemas_path . 'dcatap-1.1.json',
      'description' => t('DCAT Schema. See https://gitlab.com/european-data-portal/ckan-dcatap-schema/blob/master/ckan-dcatap-1.1.json for more awesome details.'),
    ),
  );
}

/**
 * Implements hook_open_data_schema_fill_references().
 */
function open_data_schema_dcat_open_data_schema_fill_references($schema_name, &$schema) {
  $module_path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'open_data_schema_dcat');
  switch ($schema_name) {
    case 'dcat':
      $references = array(
        'dcat:Distribution',
      );
      $files = array();
      // Process $ref keys to include referenced json file.
      foreach ($references as $key) {
        $json = $module_path . '/data/';
        if (isset($schema['properties'][$key]['anyOf'])) {
          $json = $json . $schema['properties'][$key]['anyOf'][0]['items']['$ref'];
        }
        elseif(isset($schema['properties'][$key]['$ref'])) {
          $json = $json . $schema['properties'][$key]['$ref'];
        }
        $json = file_get_contents($json);
        $json = drupal_json_decode($json);
        unset($json['$schema']);
        unset($json['id']);
        if (isset($schema['properties'][$key]['anyOf'])) {
          unset($json['title']);
          unset($schema['properties'][$key]['anyOf'][0]['items']['$ref']);
          if (isset($schema['properties'][$key]['anyOf'][0]['items']['minItems'])) {
            $schema['properties'][$key]['anyOf'][0]['minItems'] = $schema['properties'][$key]['anyOf'][0]['items']['minItems'];
          }
          if ($schema['properties'][$key]['anyOf'][0]['items']['uniqueItems']) {
            $schema['properties'][$key]['anyOf'][0]['uniqueItems'] = $schema['properties'][$key]['anyOf'][0]['items']['uniqueItems'];
          }
          $schema['properties'][$key]['anyOf'][0]['uniqueItems'] = $schema['properties'][$key]['anyOf'][0]['items']['uniqueItems'];
          $schema['properties'][$key]['anyOf'][0]['items'] = $json;
        }
        else {
          $schema['properties'][$key] = $json;
        }
      }
      break;
  }
}

/**
 * Implements hook_open_data_schema_map_xml_output_render_data_alter().
 */
function open_data_schema_dcat_open_data_schema_map_xml_output_render_data_alter(&$xml, &$api) {
  global $base_url;

  //If is dcat schema then add attributes on the xml root
  if ($api->api_schema == 'dcat') {
    $xml['@xmlns:foaf'] = "http://xmlns.com/foaf/0.1/";
    $xml['@xmlns:owl'] = "http://www.w3.org/2002/07/owl#";
    $xml['@xmlns:rdfs'] = "http://www.w3.org/2000/01/rdf-schema#";
    $xml['@xmlns:rdf'] = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
    $xml['@xmlns:dcat'] = "http://www.w3.org/ns/dcat#";
    $xml['@xmlns:dct'] = "http://purl.org/dc/terms/";
    $xml['@xmlns:adms'] = "http://www.w3.org/ns/adms#";
    $xml['@xmlns:dc'] = "http://purl.org/dc/elements/1.1/";
    $xml['@xmlns:time'] = "http://www.w3.org/2006/time#";

    //Add catalog information
    $catalog = array(
      'dct:title' => variable_get('site_name', t('Dataset')),
      'dct:description' =>  variable_get('site_slogan', t('Description')),
//      'dct:issued' => 'Issued',
//      'dct:modified' => 'Modified',
//      'dct:language' =>  'Language',
//      'dct:license' => 'License',
//      'dct:spatial' => 'Spatial',
      'foaf:homepage' => $base_url . '/search/type/dataset',
    );
    $xml = array('dcat:Catalog' => $catalog) + $xml;
  }
}
