<?php

/**
 * @file
 * Provides Schema mapping for CKAN.
 */

/**
 * Implements hook_open_data_schema().
 */
function open_data_schema_ckan_open_data_schema() {
  $path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'open_data_schema_ckan') . '/data/OGPD_JSON_Schema.json';
  return array(
    'short_name' => 'ckan',
    'title' => 'CKAN',
    'schema_file' => $path,
    'description' => t('CKAN schema. See http://ckan.org for more awesome details.'),
  );
}
