<?php

/**
 * @file
 * Provides Schema mapping for CKAN.
 */

/**
 * Implements hook_open_data_schema().
 */
function open_data_schema_ckan_open_data_schema() {
  $path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'open_data_schema_ckan') . '/data/schema_ckan.json';
  return array(
    'short_name' => 'ckan',
    'title' => 'CKAN',
    'schema_file' => $path,
    'description' => t('CKAN schema. See http://ckan.org for more awesome details.'),
  );
}

/**
 * Implements hook_open_data_schema_map_results_alter().
 */
function open_data_schema_ckan_open_data_schema_map_results_alter(&$result, $machine_name, $api_schema) {
  if ($api_schema == 'ckan') {
    // CKAN expects results wrapped in help, success, result.
    $result = array(
      'help' => '',
      'success' => TRUE,
      'result' => $result,
    );
    if (!$result['result']) {
      $result['success'] = FALSE;
    }
    if ($machine_name == 'ckan_package_show') {
      $result['help'] = t('Return the metadata of a dataset (package) and its resources. :param id: the id or name of the dataset :type id: string');
    }
    elseif ($machine_name == 'ckan_revision_list') {
      $result['help'] = t("Return a list of the IDs of the site's revisions.\n\n :rtype: list of strings.");
      foreach ($result['result'] as $num => $data) {
        // This endpoint just produces a list.
        foreach ($data as $api_field => $item) {
          $list[] = $item;
        }
      }
      $result['result'] = $list;
    }
    elseif ($machine_name == 'ckan_package_list') {      
      $result['help'] = t("Return a list of the names of the site's datasets (packages).\n\n :param limit: if given, the list of datasets will be broken into pages of\n at most ``limit`` datasets per page and only one page will be returned\n at a time (optional)\n :type limit: int\n :param offset: when ``limit`` is given, the offset to start returning packages from\n :type offset: int\n\n :rtype: list of strings\n\n");
      foreach ($result['result'] as $num => $data) {        
        $list[] = $data['name'];        
      }

      $result['result'] = $list;
    }    
  }
}
