<?php

/**
 * @file
 * Maps entity types to Open Data schemas.
 */

/**
 * TODO:
 *
 * register schema
 * add table
 * create form
 * render output
 * featurize
 */

/**
 * Implements hook_menu().
 */
function open_data_schema_map_menu() {
  $items = array();
  $pre = 'admin/config/services/odsm';

  $items[$pre] = array(
    'title' => 'Open Data Schema Mapper',
    'description' => 'Map Drupal structures to Open Data specfications',
    'page callback' => 'open_data_schema_mapper_page_overview',
    'access arguments' => array('administer open data schema mapper.'),
  );
  $items[$pre . '/overview'] = array(
    'title' => 'Overview',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items[$pre . '/add/api'] = array(
    'title' => 'Add API',
    'description' => 'Add a new API Endpoint',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('open_data_schema_map_add_api'),
    'access arguments' => array('administer open data schema mapper.'),
    'type' => MENU_LOCAL_ACTION,
  );
  $items[$pre . '/edit/%open_data_schema_map_api'] = array(
    'title' => 'Edit API',
    'description' => 'Edit an existing API Endpoint',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('open_data_schema_map_add_api', 5),
    'access arguments' => array('administer open data schema mapper.'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function open_data_schema_map_permission() {
  return array(
    'administer open data schema mapper' => array(
      'title' => t('Administer Open Data Schema Mapper'),
      'description' => t('Make and update open data schema maps'),
      'restrict access' => TRUE,
    ));
}

/**
 * Registers declared schemas.
 */
function open_data_schema_map_register() {
  static $schemas = array();
  if ($schemas) {
    return $schemas;
  }
  foreach (module_implements('open_data_schema') as $module) {
    $data = module_invoke($module, 'open_data_schema');
    $schemas[$data['short_name']] = $data;
  }
  return $schemas;
}

/**
 * Implements hook_help().
 */
function open_data_schema_map_help($path, $arg) {
  switch ($path) {
    case 'admin/config/services/odsm':
      return t('Create APIs using Drupal entities that map to Open Data specifications.');
  }
}


/**
 * Callback for ODSM overiew page.
 */
function open_data_schema_mapper_page_overview() {
  $form = array();
  $apis = open_data_schema_map_apis();
  $list = array();
  foreach ($apis as $name => $data) {
    $list[] = $data;
  }
  $header = array();
  $header[] = t('title');
  $header[] = t('Endpoint');
  $header[] = t('Schema');
  $header[] = t('Entity');
  $header[] = t('Bundle');
  $header[] = t('Edit');
  $header[] = t('Delete');
  $rows = $list;
  return array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
    '#attributes' => array('class' => array('search-api-overview')),
    '#empty' => t('There are no search servers or indexes defined yet.'),
  );
}

/**
 * Callback for primary menu page.
 */
function open_data_schema_map_add_api(array $form, array &$form_state, $api= NULL) {
  dpm($api);
  drupal_set_title(t('Add API'));
  $apis = open_data_schema_map_apis();
  $schemas = open_data_schema_map_register();
  if (!$schemas) {
    $form['empty'] = array(
      '#type' => 'item',
      '#title' => 'No Available Schemas',
      '#markup' => t('You must enable an Open Data schema to add an endpoint.'),
    );
    return $form;
  }
  $list = array();
  foreach ($schemas as $name => $data) {
    $list[$name] = $data['title'];
  }
  $markup = t('No APIs created.');
  if ($list) {
    $markup = t('Choose from the available APIs:') . theme('item_list', $list);
  }
  $entity_types = entity_get_info();
  foreach ($entity_types as $entity_name => $entity_info) {
    $entity_list[$entity_name] = $entity_info['label'];
  }
  $selected_entity = '';
  $selected_schema = '';
  if (isset($form_state['triggering_element']['#name']) && $name = $form_state['triggering_element']['#name']) {
    if ($name == 'schema') {
      $selected_schema = $form_state['triggering_element']['#value'];
    }
    elseif ($name == 'type') {
      $selected_entity = $form_state['triggering_element']['#value'];
    }
  }
  $form['name'] = array(
    '#title' => 'Title',
    '#type' => 'textfield',
    '#description' => t('Add an administrative title.'),
    '#required' => TRUE,
  );
  $form['machine_name'] = array(
    '#type' => 'machine_name',
    '#maxlength' => 50,
    '#machine_name' => array(
      'exists' => 'open_data_schema_map_api_exist',
    ),
  );
  $form['type'] = array(
    '#title' => 'Entity Type',
    '#type' => 'select',
    '#description' => t('Entity type.'),
    '#options' => $entity_list,
    '#required' => TRUE,
    '#ajax' => array(
      'callback' => 'open_data_schema_map_bundle_ajax_callback',
      'wrapper' => 'open-data-schema-map-bundle-options',
    ),
  );
  $bundle_list = array();
  if ($selected_entity) {
    foreach ($entity_types[$selected_entity]['bundles'] as $bundle_name => $bundle_data) {
      $bundle_list[$bundle_name] = $bundle_data['label'];
    }
    $form['bundle'] = array(
      '#title' => 'Bundle',
      '#type' => 'select',
      '#description' => t('Entity type bundle.'),
      '#options' => $bundle_list,
      '#required' => TRUE,
    );
  }
  else {
    $form['bundle'] = array(
      '#title' => 'Bundle',
      '#type' => 'item',
      '#markup' => t('Select an entity type'),
      '#required' => TRUE,
    );
  }
  $form['bundle']['#prefix'] = '<div id="open-data-schema-map-bundle-options">';
  $form['bundle']['#suffix'] = '</div>';
  $form['endpoint'] = array(
    '#title' => 'Endpoint',
    '#type' => 'textfield',
    '#description' => t('Add and enpoint ie "api/3/action/package_show".'),
    '#required' => TRUE,
  );
  $form['schema'] = array(
    '#title' => 'Schema',
    '#type' => 'select',
    '#description' => t('Select from the available schemas.'),
    '#options' => $list,
    '#required' => TRUE,
    '#ajax' => array(
      'callback' => 'open_data_schema_map_mapping_ajax_callback',
      'wrapper' => 'open-data-schema-map-mapping-options',
    ),
  );
  if ($selected_schema) {
    foreach ($entity_types[$selected_entity]['bundles'] as $bundle_name => $bundle_data) {
      $bundle_list[$bundle_name] = $bundle_data['label'];
    }
    $form['mapping'] = array(
      '#title' => 'Mapping',
      '#type' => 'item',
      '#markup' => t('You selected a schema.'),
      '#required' => TRUE,
    );
  }
  else {
    $form['mapping'] = array(
      '#title' => 'Mapping',
      '#type' => 'item',
      '#markup' => t('Select a schema.'),
      '#required' => TRUE,
    );
  }
  $form['mapping']['#prefix'] = '<div id="open-data-schema-map-mapping-options">';
  $form['mapping']['#suffix'] = '</div>';
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Create API'),
  );
  return $form;
}

/**
 * Form AJAX handler for search_api_admin_add_server().
 *
 * Just returns the "options" array of the already built form array.
 */
function open_data_schema_map_bundle_ajax_callback(array $form, array &$form_state) {
  return $form['bundle'];
}

/**
 * Form AJAX handler for search_api_admin_add_server().
 *
 * Just returns the "options" array of the already built form array.
 */
function open_data_schema_map_mapping_ajax_callback(array $form, array &$form_state) {
  return $form['mapping'];
}

function open_data_schema_map_add_api_submit($form, $form_state) {
  $values = $form_state['values'];
  unset($values['submit']);
  unset($values['form_build_id']);
  unset($values['form_id']);
  unset($values['form_token']);
  unset($values['op']);
  drupal_write_record('open_data_schema_map', $values);
  drupal_goto('admin/config/services/odsm/edit/' . $values['machine_name']);
}

/**
 * Lists APIs created with this module.
 */
function open_data_schema_map_apis() {
  return array(
    'none' => array(
      'title' => 'Title',
      'endpoint' => 'Endpoint',
      'schema' => 'Schema',
      'entity' => 'Entity',
      'bundle' => 'bun',
      'args' => 'arge',
    ),
  );
}

/**
 * Determines whether a machine name exists.
 *
 * @param string $machine_name
 *   API machine name.
 */
function open_data_schema_map_api_exist($machine_name) {
  return FALSE;
}

/**
 * Loads API.
 *
 * @param string $machine_name
 *   API machine name.
 *
 * @return object
 *   API object.
 */
function open_data_schema_map_api_load($machine_name) {
  dpm('load');
  dpm($machine_name);
  return array(
    'none' => array(
      'title' => 'Title',
      'endpoint' => 'Endpoint',
      'schema' => 'Schema',
      'entity' => 'Entity',
      'bundle' => 'bun',
      'args' => 'arge',
    ),
  );
}

function open_data_schema_map_add_edit($api) {
  $form = 
  $form['empty'] = array(
    '#type' => 'item',
    '#title' => 'o Available Schemas',
    '#markup' => t('You must enable an Open Data schema to add an endpoint.'),
  );
  return $form;
}
