<?php

/**
 * @file
 * Provides XML output for Open Data Schema Map.
 */
$module_path = drupal_get_path('module', 'open_data_schema_map_xml_output');
include implode('/', array($module_path, 'autoload.php'));

use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer;

define("DEFAULT_XML_ROOT", "records");
define("DEFAULT_XML_TAG", "record");

/**
 * Implements hook_libraries_info().
 */
function open_data_schema_map_xml_output_libraries_info() {
  $libraries['symfonyserializer'] = array(
    'name' => 'Simfony Serializer',
    'vendor url' => 'https://github.com/symfony/serializer',
    'download url' => 'https://github.com/symfony/serializer/zipball/master',
    'version' => 'master',
    'files' => array(),
  );
  return $libraries;
}

/**
 * Implements hook_odsm_form_alter().
 */
function open_data_schema_map_xml_output_odsm_form_alter(&$form, $api) {
  $form['xml_root'] = array(
    '#title' => 'XML Root',
    '#type' => 'textfield',
    '#description' => t('(XML only) Enter the XML Root Name (default: records).'),
    '#required' => False,
    '#weight' => 3,
    '#states' => array(
      'visible' => array(
        ':input[name="outputformat"]' => array('value' => 'xml'),
      ),
    ),
  );
  $form['xml_defaulttag'] = array(
    '#title' => 'XML Default Node',
    '#type' => 'textfield',
    '#description' => t('(XML only) Enter the XML Default Node Name (default: record).'),
    '#required' => False,
    '#weight' => 4,
    '#states' => array(
      'visible' => array(
        ':input[name="outputformat"]' => array('value' => 'xml'),
      ),
    ),
  );
}

/**
 * Implements hook_odsm_page_overview_alter().
 */
function open_data_schema_map_xml_output_odsm_page_overview_alter(&$data) {
  unset($data['xml_root']);
  unset($data['xml_defaulttag']);
}

/**
 * Implements hook_odsm_output_format().
 */
function open_data_schema_map_xml_output_odsm_output_format() {
  return array(
    'xml' => array(
      'callback' => 'open_data_schema_map_xml_output_render',
      'headers' => array(
        'Content-Type' => 'application/xml',
      ),
    ),
  );
}

/**
 * Render function for hook_odsm_output_format implementation
 */

function open_data_schema_map_xml_output_render($api, $result) {
  // We are returning XML, so tell the browser.
  drupal_add_http_header('Content-Type', 'application/xml');
  $xml_root = DEFAULT_XML_ROOT;
  $xml_defaulttag = DEFAULT_XML_TAG;
  if (isset($api->xml_root) && $api->xml_root != '') {
    $xml_root = $api->xml_root;
  }
  if (isset($api->xml_defaulttag) && $api->xml_defaulttag != '') {
    $xml_defaulttag = $api->xml_defaulttag;
  }

  $xml = array();
  $xml[$xml_defaulttag] = $result;
  unset($xml[$xml_defaulttag]['key']);

  $encoders = array(
    new XmlEncoder($xml_root)
  );
  
  $normalizers = array(new GetSetMethodNormalizer());
  $serializer = new Serializer($normalizers, $encoders);
  
  return $serializer->serialize($xml, 'xml');
}

